version: '3.7'
services:
  postgresql:
    image: postgres:9.6.21
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=aisafa
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
